version: '3.9'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'


  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=130468
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    tty: true
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy


  selery:
    build: .
    tty: true
    command: celery -A config worker -l INFO --loglevel warning
    depends_on:
      - redis
      - app


  selery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data: