# Generated by Django 4.2.6 on 2023-10-30 12:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='action',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='execution_time_minutes',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='frequency_days',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_rewarding',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='related_habit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_action',
            field=models.CharField(default='default_value', max_length=255, verbose_name='действие'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('DAILY', 'каждый день'), ('WEEKLY', 'раз в неделю')], default='DAILY', max_length=15, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='habit',
            name='pleasant_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Приятная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение в секундах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.DeleteModel(
            name='HabitLog',
        ),
    ]
