# Generated by Django 4.2.6 on 2023-11-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_remove_habit_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('owner',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='next_repost',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следуйщей отправки, не изменять!'),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_Habit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привычка, но не для приятных'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_action',
            field=models.CharField(default='default_value', max_length=255, verbose_name='действие, которое представляет из себя привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('DAILY', 'каждый день'), ('WEEKLY', 'раз в неделю')], default='DAILY', max_length=15, verbose_name='Периодичность выполнения привычки для напоминания в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=255, verbose_name='место, где нужно выполнять прывычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='Время, когда нужно делать привычку'),
        ),
    ]
