# Generated by Django 4.2.6 on 2023-11-07 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0003_alter_habit_options_habit_next_repost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_Habit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение привычки в секундах'),
        ),
    ]
