# Generated by Django 4.2.6 on 2023-11-09 12:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0004_alter_habit_is_public_alter_habit_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='next_repost',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='pleasant_habit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публичности привычки (в общем доступе)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=255, verbose_name='место, в котором нужно выполнять прывычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_Habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='Вознаграждение, которым пользователь должен себя вознаградить после выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='Время, когда необходимо выполнять привычку'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение пользователем привычки в секундах'),
        ),
    ]
