# Generated by Django 4.2.6 on 2023-11-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habit_next_repost_remove_habit_pleasant_habit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
    ]
